# Generated by Django 5.0 on 2024-05-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
